/*
 * Automatically generated, but now edited manually
 * Busybox version: 1.22.1
 */
#define AUTOCONF_TIMESTAMP "2014-10-26 09:24:54 CDT"

#define CONFIG_HAVE_DOT_CONFIG 1
#define ENABLE_HAVE_DOT_CONFIG 1
#ifdef MAKE_SUID
# define IF_HAVE_DOT_CONFIG(...) __VA_ARGS__ "CONFIG_HAVE_DOT_CONFIG"
#else
# define IF_HAVE_DOT_CONFIG(...) __VA_ARGS__
#endif
#define IF_NOT_HAVE_DOT_CONFIG(...)

/*
 * Busybox Settings
 */

/*
 * General Configuration
 */
#undef CONFIG_DESKTOP
#define ENABLE_DESKTOP 0
#define IF_DESKTOP(...)
#define IF_NOT_DESKTOP(...) __VA_ARGS__
#undef CONFIG_EXTRA_COMPAT
#define ENABLE_EXTRA_COMPAT 0
#define IF_EXTRA_COMPAT(...)
#define IF_NOT_EXTRA_COMPAT(...) __VA_ARGS__
#define CONFIG_INCLUDE_SUSv2 1
#define ENABLE_INCLUDE_SUSv2 1
#ifdef MAKE_SUID
# define IF_INCLUDE_SUSv2(...) __VA_ARGS__ "CONFIG_INCLUDE_SUSv2"
#else
# define IF_INCLUDE_SUSv2(...) __VA_ARGS__
#endif
#define IF_NOT_INCLUDE_SUSv2(...)
#define CONFIG_USE_PORTABLE_CODE 1
#define ENABLE_USE_PORTABLE_CODE 1
#ifdef MAKE_SUID
# define IF_USE_PORTABLE_CODE(...) __VA_ARGS__ "CONFIG_USE_PORTABLE_CODE"
#else
# define IF_USE_PORTABLE_CODE(...) __VA_ARGS__
#endif
#define IF_NOT_USE_PORTABLE_CODE(...)
#undef CONFIG_PLATFORM_LINUX
#define ENABLE_PLATFORM_LINUX 0
#define IF_PLATFORM_LINUX(...)
#define IF_NOT_PLATFORM_LINUX(...) __VA_ARGS__
#define CONFIG_FEATURE_BUFFERS_USE_MALLOC 1
#define ENABLE_FEATURE_BUFFERS_USE_MALLOC 1
#ifdef MAKE_SUID
# define IF_FEATURE_BUFFERS_USE_MALLOC(...) __VA_ARGS__ "CONFIG_FEATURE_BUFFERS_USE_MALLOC"
#else
# define IF_FEATURE_BUFFERS_USE_MALLOC(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_BUFFERS_USE_MALLOC(...)
#undef CONFIG_FEATURE_BUFFERS_GO_ON_STACK
#define ENABLE_FEATURE_BUFFERS_GO_ON_STACK 0
#define IF_FEATURE_BUFFERS_GO_ON_STACK(...)
#define IF_NOT_FEATURE_BUFFERS_GO_ON_STACK(...) __VA_ARGS__
#undef CONFIG_FEATURE_BUFFERS_GO_IN_BSS
#define ENABLE_FEATURE_BUFFERS_GO_IN_BSS 0
#define IF_FEATURE_BUFFERS_GO_IN_BSS(...)
#define IF_NOT_FEATURE_BUFFERS_GO_IN_BSS(...) __VA_ARGS__
#define CONFIG_SHOW_USAGE 1
#define ENABLE_SHOW_USAGE 1
#ifdef MAKE_SUID
# define IF_SHOW_USAGE(...) __VA_ARGS__ "CONFIG_SHOW_USAGE"
#else
# define IF_SHOW_USAGE(...) __VA_ARGS__
#endif
#define IF_NOT_SHOW_USAGE(...)
#define CONFIG_FEATURE_VERBOSE_USAGE 1
#define ENABLE_FEATURE_VERBOSE_USAGE 1
#ifdef MAKE_SUID
# define IF_FEATURE_VERBOSE_USAGE(...) __VA_ARGS__ "CONFIG_FEATURE_VERBOSE_USAGE"
#else
# define IF_FEATURE_VERBOSE_USAGE(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_VERBOSE_USAGE(...)
#undef CONFIG_FEATURE_COMPRESS_USAGE
#define ENABLE_FEATURE_COMPRESS_USAGE 0
#define IF_FEATURE_COMPRESS_USAGE(...)
#define IF_NOT_FEATURE_COMPRESS_USAGE(...) __VA_ARGS__
#undef CONFIG_FEATURE_INSTALLER
#define ENABLE_FEATURE_INSTALLER 0
#define IF_FEATURE_INSTALLER(...)
#define IF_NOT_FEATURE_INSTALLER(...) __VA_ARGS__
#undef CONFIG_INSTALL_NO_USR
#define ENABLE_INSTALL_NO_USR 0
#define IF_INSTALL_NO_USR(...)
#define IF_NOT_INSTALL_NO_USR(...) __VA_ARGS__
#undef CONFIG_LOCALE_SUPPORT
#define ENABLE_LOCALE_SUPPORT 0
#define IF_LOCALE_SUPPORT(...)
#define IF_NOT_LOCALE_SUPPORT(...) __VA_ARGS__
#define CONFIG_UNICODE_SUPPORT 1
#define ENABLE_UNICODE_SUPPORT 1
#ifdef MAKE_SUID
# define IF_UNICODE_SUPPORT(...) __VA_ARGS__ "CONFIG_UNICODE_SUPPORT"
#else
# define IF_UNICODE_SUPPORT(...) __VA_ARGS__
#endif
#define IF_NOT_UNICODE_SUPPORT(...)
#undef CONFIG_UNICODE_USING_LOCALE
#define ENABLE_UNICODE_USING_LOCALE 0
#define IF_UNICODE_USING_LOCALE(...)
#define IF_NOT_UNICODE_USING_LOCALE(...) __VA_ARGS__
#undef CONFIG_FEATURE_CHECK_UNICODE_IN_ENV
#define ENABLE_FEATURE_CHECK_UNICODE_IN_ENV 0
#define IF_FEATURE_CHECK_UNICODE_IN_ENV(...)
#define IF_NOT_FEATURE_CHECK_UNICODE_IN_ENV(...) __VA_ARGS__
#define CONFIG_SUBST_WCHAR 63
#define ENABLE_SUBST_WCHAR 1
#ifdef MAKE_SUID
# define IF_SUBST_WCHAR(...) __VA_ARGS__ "CONFIG_SUBST_WCHAR"
#else
# define IF_SUBST_WCHAR(...) __VA_ARGS__
#endif
#define IF_NOT_SUBST_WCHAR(...)
#define CONFIG_LAST_SUPPORTED_WCHAR 767
#define ENABLE_LAST_SUPPORTED_WCHAR 1
#ifdef MAKE_SUID
# define IF_LAST_SUPPORTED_WCHAR(...) __VA_ARGS__ "CONFIG_LAST_SUPPORTED_WCHAR"
#else
# define IF_LAST_SUPPORTED_WCHAR(...) __VA_ARGS__
#endif
#define IF_NOT_LAST_SUPPORTED_WCHAR(...)
#undef CONFIG_UNICODE_COMBINING_WCHARS
#define ENABLE_UNICODE_COMBINING_WCHARS 0
#define IF_UNICODE_COMBINING_WCHARS(...)
#define IF_NOT_UNICODE_COMBINING_WCHARS(...) __VA_ARGS__
#undef CONFIG_UNICODE_WIDE_WCHARS
#define ENABLE_UNICODE_WIDE_WCHARS 0
#define IF_UNICODE_WIDE_WCHARS(...)
#define IF_NOT_UNICODE_WIDE_WCHARS(...) __VA_ARGS__
#undef CONFIG_UNICODE_BIDI_SUPPORT
#define ENABLE_UNICODE_BIDI_SUPPORT 0
#define IF_UNICODE_BIDI_SUPPORT(...)
#define IF_NOT_UNICODE_BIDI_SUPPORT(...) __VA_ARGS__
#undef CONFIG_UNICODE_NEUTRAL_TABLE
#define ENABLE_UNICODE_NEUTRAL_TABLE 0
#define IF_UNICODE_NEUTRAL_TABLE(...)
#define IF_NOT_UNICODE_NEUTRAL_TABLE(...) __VA_ARGS__
#undef CONFIG_UNICODE_PRESERVE_BROKEN
#define ENABLE_UNICODE_PRESERVE_BROKEN 0
#define IF_UNICODE_PRESERVE_BROKEN(...)
#define IF_NOT_UNICODE_PRESERVE_BROKEN(...) __VA_ARGS__
#define CONFIG_LONG_OPTS 1
#define ENABLE_LONG_OPTS 1
#ifdef MAKE_SUID
# define IF_LONG_OPTS(...) __VA_ARGS__ "CONFIG_LONG_OPTS"
#else
# define IF_LONG_OPTS(...) __VA_ARGS__
#endif
#define IF_NOT_LONG_OPTS(...)
#define CONFIG_FEATURE_DEVPTS 1
#define ENABLE_FEATURE_DEVPTS 1
#ifdef MAKE_SUID
# define IF_FEATURE_DEVPTS(...) __VA_ARGS__ "CONFIG_FEATURE_DEVPTS"
#else
# define IF_FEATURE_DEVPTS(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_DEVPTS(...)
#undef CONFIG_FEATURE_CLEAN_UP
#define ENABLE_FEATURE_CLEAN_UP 0
#define IF_FEATURE_CLEAN_UP(...)
#define IF_NOT_FEATURE_CLEAN_UP(...) __VA_ARGS__
#define CONFIG_FEATURE_UTMP 1
#define ENABLE_FEATURE_UTMP 1
#ifdef MAKE_SUID
# define IF_FEATURE_UTMP(...) __VA_ARGS__ "CONFIG_FEATURE_UTMP"
#else
# define IF_FEATURE_UTMP(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_UTMP(...)
#define CONFIG_FEATURE_WTMP 1
#define ENABLE_FEATURE_WTMP 1
#ifdef MAKE_SUID
# define IF_FEATURE_WTMP(...) __VA_ARGS__ "CONFIG_FEATURE_WTMP"
#else
# define IF_FEATURE_WTMP(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_WTMP(...)
#define CONFIG_FEATURE_PIDFILE 1
#define ENABLE_FEATURE_PIDFILE 1
#ifdef MAKE_SUID
# define IF_FEATURE_PIDFILE(...) __VA_ARGS__ "CONFIG_FEATURE_PIDFILE"
#else
# define IF_FEATURE_PIDFILE(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_PIDFILE(...)
#define CONFIG_PID_FILE_PATH "/var/run"
#define ENABLE_PID_FILE_PATH 1
#ifdef MAKE_SUID
# define IF_PID_FILE_PATH(...) __VA_ARGS__ "CONFIG_PID_FILE_PATH"
#else
# define IF_PID_FILE_PATH(...) __VA_ARGS__
#endif
#define IF_NOT_PID_FILE_PATH(...)
#define CONFIG_FEATURE_SUID 1
#define ENABLE_FEATURE_SUID 1
#ifdef MAKE_SUID
# define IF_FEATURE_SUID(...) __VA_ARGS__ "CONFIG_FEATURE_SUID"
#else
# define IF_FEATURE_SUID(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_SUID(...)
#define CONFIG_FEATURE_SUID_CONFIG 1
#define ENABLE_FEATURE_SUID_CONFIG 1
#ifdef MAKE_SUID
# define IF_FEATURE_SUID_CONFIG(...) __VA_ARGS__ "CONFIG_FEATURE_SUID_CONFIG"
#else
# define IF_FEATURE_SUID_CONFIG(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_SUID_CONFIG(...)
#define CONFIG_FEATURE_SUID_CONFIG_QUIET 1
#define ENABLE_FEATURE_SUID_CONFIG_QUIET 1
#ifdef MAKE_SUID
# define IF_FEATURE_SUID_CONFIG_QUIET(...) __VA_ARGS__ "CONFIG_FEATURE_SUID_CONFIG_QUIET"
#else
# define IF_FEATURE_SUID_CONFIG_QUIET(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_SUID_CONFIG_QUIET(...)
#undef CONFIG_SELINUX
#define ENABLE_SELINUX 0
#define IF_SELINUX(...)
#define IF_NOT_SELINUX(...) __VA_ARGS__
#undef CONFIG_FEATURE_PREFER_APPLETS
#define ENABLE_FEATURE_PREFER_APPLETS 0
#define IF_FEATURE_PREFER_APPLETS(...)
#define IF_NOT_FEATURE_PREFER_APPLETS(...) __VA_ARGS__
#define CONFIG_BUSYBOX_EXEC_PATH "/proc/self/exe"
#define ENABLE_BUSYBOX_EXEC_PATH 1
#ifdef MAKE_SUID
# define IF_BUSYBOX_EXEC_PATH(...) __VA_ARGS__ "CONFIG_BUSYBOX_EXEC_PATH"
#else
# define IF_BUSYBOX_EXEC_PATH(...) __VA_ARGS__
#endif
#define IF_NOT_BUSYBOX_EXEC_PATH(...)
#undef CONFIG_FEATURE_SYSLOG
#define ENABLE_FEATURE_SYSLOG 0
#define IF_FEATURE_SYSLOG(...)
#define IF_NOT_FEATURE_SYSLOG(...) __VA_ARGS__
#undef CONFIG_FEATURE_HAVE_RPC
#define ENABLE_FEATURE_HAVE_RPC 0
#define IF_FEATURE_HAVE_RPC(...)
#define IF_NOT_FEATURE_HAVE_RPC(...) __VA_ARGS__

/*
 * Build Options
 */
#undef CONFIG_STATIC
#define ENABLE_STATIC 0
#define IF_STATIC(...)
#define IF_NOT_STATIC(...) __VA_ARGS__
#undef CONFIG_PIE
#define ENABLE_PIE 0
#define IF_PIE(...)
#define IF_NOT_PIE(...) __VA_ARGS__
#define CONFIG_NOMMU 1
#define ENABLE_NOMMU 1
#ifdef MAKE_SUID
# define IF_NOMMU(...) __VA_ARGS__ "CONFIG_NOMMU"
#else
# define IF_NOMMU(...) __VA_ARGS__
#endif
#define IF_NOT_NOMMU(...)
#undef CONFIG_BUILD_LIBBUSYBOX
#define ENABLE_BUILD_LIBBUSYBOX 0
#define IF_BUILD_LIBBUSYBOX(...)
#define IF_NOT_BUILD_LIBBUSYBOX(...) __VA_ARGS__
#undef CONFIG_FEATURE_INDIVIDUAL
#define ENABLE_FEATURE_INDIVIDUAL 0
#define IF_FEATURE_INDIVIDUAL(...)
#define IF_NOT_FEATURE_INDIVIDUAL(...) __VA_ARGS__
#undef CONFIG_FEATURE_SHARED_BUSYBOX
#define ENABLE_FEATURE_SHARED_BUSYBOX 0
#define IF_FEATURE_SHARED_BUSYBOX(...)
#define IF_NOT_FEATURE_SHARED_BUSYBOX(...) __VA_ARGS__
#undef CONFIG_LFS
#define ENABLE_LFS 0
#define IF_LFS(...)
#define IF_NOT_LFS(...) __VA_ARGS__
#define CONFIG_CROSS_COMPILER_PREFIX ""
#define ENABLE_CROSS_COMPILER_PREFIX 1
#ifdef MAKE_SUID
# define IF_CROSS_COMPILER_PREFIX(...) __VA_ARGS__ "CONFIG_CROSS_COMPILER_PREFIX"
#else
# define IF_CROSS_COMPILER_PREFIX(...) __VA_ARGS__
#endif
#define IF_NOT_CROSS_COMPILER_PREFIX(...)
#define CONFIG_SYSROOT ""
#define ENABLE_SYSROOT 1
#ifdef MAKE_SUID
# define IF_SYSROOT(...) __VA_ARGS__ "CONFIG_SYSROOT"
#else
# define IF_SYSROOT(...) __VA_ARGS__
#endif
#define IF_NOT_SYSROOT(...)
#define CONFIG_EXTRA_CFLAGS ""
#define ENABLE_EXTRA_CFLAGS 1
#ifdef MAKE_SUID
# define IF_EXTRA_CFLAGS(...) __VA_ARGS__ "CONFIG_EXTRA_CFLAGS"
#else
# define IF_EXTRA_CFLAGS(...) __VA_ARGS__
#endif
#define IF_NOT_EXTRA_CFLAGS(...)
#define CONFIG_EXTRA_LDFLAGS ""
#define ENABLE_EXTRA_LDFLAGS 1
#ifdef MAKE_SUID
# define IF_EXTRA_LDFLAGS(...) __VA_ARGS__ "CONFIG_EXTRA_LDFLAGS"
#else
# define IF_EXTRA_LDFLAGS(...) __VA_ARGS__
#endif
#define IF_NOT_EXTRA_LDFLAGS(...)
#define CONFIG_EXTRA_LDLIBS ""
#define ENABLE_EXTRA_LDLIBS 1
#ifdef MAKE_SUID
# define IF_EXTRA_LDLIBS(...) __VA_ARGS__ "CONFIG_EXTRA_LDLIBS"
#else
# define IF_EXTRA_LDLIBS(...) __VA_ARGS__
#endif
#define IF_NOT_EXTRA_LDLIBS(...)

/*
 * Debugging Options
 */
#undef CONFIG_DEBUG
#define ENABLE_DEBUG 0
#define IF_DEBUG(...)
#define IF_NOT_DEBUG(...) __VA_ARGS__
#undef CONFIG_DEBUG_PESSIMIZE
#define ENABLE_DEBUG_PESSIMIZE 0
#define IF_DEBUG_PESSIMIZE(...)
#define IF_NOT_DEBUG_PESSIMIZE(...) __VA_ARGS__
#undef CONFIG_WERROR
#define ENABLE_WERROR 0
#define IF_WERROR(...)
#define IF_NOT_WERROR(...) __VA_ARGS__
#define CONFIG_NO_DEBUG_LIB 1
#define ENABLE_NO_DEBUG_LIB 1
#ifdef MAKE_SUID
# define IF_NO_DEBUG_LIB(...) __VA_ARGS__ "CONFIG_NO_DEBUG_LIB"
#else
# define IF_NO_DEBUG_LIB(...) __VA_ARGS__
#endif
#define IF_NOT_NO_DEBUG_LIB(...)
#undef CONFIG_DMALLOC
#define ENABLE_DMALLOC 0
#define IF_DMALLOC(...)
#define IF_NOT_DMALLOC(...) __VA_ARGS__
#undef CONFIG_EFENCE
#define ENABLE_EFENCE 0
#define IF_EFENCE(...)
#define IF_NOT_EFENCE(...) __VA_ARGS__

/*
 * Busybox Library Tuning
 */
#undef CONFIG_FEATURE_ETC_NETWORKS
#define ENABLE_FEATURE_ETC_NETWORKS 0
#define IF_FEATURE_ETC_NETWORKS(...)
#define IF_NOT_FEATURE_ETC_NETWORKS(...) __VA_ARGS__
#undef CONFIG_FEATURE_USE_TERMIOS
#define ENABLE_FEATURE_USE_TERMIOS 0
#define IF_FEATURE_USE_TERMIOS(...)
#define IF_NOT_FEATURE_USE_TERMIOS(...) __VA_ARGS__
#define CONFIG_FEATURE_EDITING 1
#define ENABLE_FEATURE_EDITING 1
#ifdef MAKE_SUID
# define IF_FEATURE_EDITING(...) __VA_ARGS__ "CONFIG_FEATURE_EDITING"
#else
# define IF_FEATURE_EDITING(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_EDITING(...)
#define CONFIG_FEATURE_EDITING_MAX_LEN 1024
#define ENABLE_FEATURE_EDITING_MAX_LEN 1
#ifdef MAKE_SUID
# define IF_FEATURE_EDITING_MAX_LEN(...) __VA_ARGS__ "CONFIG_FEATURE_EDITING_MAX_LEN"
#else
# define IF_FEATURE_EDITING_MAX_LEN(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_EDITING_MAX_LEN(...)
#undef CONFIG_FEATURE_EDITING_VI
#define ENABLE_FEATURE_EDITING_VI 0
#define IF_FEATURE_EDITING_VI(...)
#define IF_NOT_FEATURE_EDITING_VI(...) __VA_ARGS__
#define CONFIG_FEATURE_EDITING_HISTORY 255
#define ENABLE_FEATURE_EDITING_HISTORY 1
#ifdef MAKE_SUID
# define IF_FEATURE_EDITING_HISTORY(...) __VA_ARGS__ "CONFIG_FEATURE_EDITING_HISTORY"
#else
# define IF_FEATURE_EDITING_HISTORY(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_EDITING_HISTORY(...)
#define CONFIG_FEATURE_EDITING_SAVEHISTORY 1
#define ENABLE_FEATURE_EDITING_SAVEHISTORY 1
#ifdef MAKE_SUID
# define IF_FEATURE_EDITING_SAVEHISTORY(...) __VA_ARGS__ "CONFIG_FEATURE_EDITING_SAVEHISTORY"
#else
# define IF_FEATURE_EDITING_SAVEHISTORY(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_EDITING_SAVEHISTORY(...)
#undef CONFIG_FEATURE_EDITING_SAVE_ON_EXIT
#define ENABLE_FEATURE_EDITING_SAVE_ON_EXIT 0
#define IF_FEATURE_EDITING_SAVE_ON_EXIT(...)
#define IF_NOT_FEATURE_EDITING_SAVE_ON_EXIT(...) __VA_ARGS__
#define CONFIG_FEATURE_REVERSE_SEARCH 1
#define ENABLE_FEATURE_REVERSE_SEARCH 1
#ifdef MAKE_SUID
# define IF_FEATURE_REVERSE_SEARCH(...) __VA_ARGS__ "CONFIG_FEATURE_REVERSE_SEARCH"
#else
# define IF_FEATURE_REVERSE_SEARCH(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_REVERSE_SEARCH(...)
#define CONFIG_FEATURE_TAB_COMPLETION 1
#define ENABLE_FEATURE_TAB_COMPLETION 1
#ifdef MAKE_SUID
# define IF_FEATURE_TAB_COMPLETION(...) __VA_ARGS__ "CONFIG_FEATURE_TAB_COMPLETION"
#else
# define IF_FEATURE_TAB_COMPLETION(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_TAB_COMPLETION(...)
#undef CONFIG_FEATURE_USERNAME_COMPLETION
#define ENABLE_FEATURE_USERNAME_COMPLETION 0
#define IF_FEATURE_USERNAME_COMPLETION(...)
#define IF_NOT_FEATURE_USERNAME_COMPLETION(...) __VA_ARGS__
#define CONFIG_FEATURE_EDITING_FANCY_PROMPT 1
#define ENABLE_FEATURE_EDITING_FANCY_PROMPT 1
#ifdef MAKE_SUID
# define IF_FEATURE_EDITING_FANCY_PROMPT(...) __VA_ARGS__ "CONFIG_FEATURE_EDITING_FANCY_PROMPT"
#else
# define IF_FEATURE_EDITING_FANCY_PROMPT(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_EDITING_FANCY_PROMPT(...)
#undef CONFIG_FEATURE_EDITING_ASK_TERMINAL
#define ENABLE_FEATURE_EDITING_ASK_TERMINAL 0
#define IF_FEATURE_EDITING_ASK_TERMINAL(...)
#define IF_NOT_FEATURE_EDITING_ASK_TERMINAL(...) __VA_ARGS__
#define CONFIG_FEATURE_NON_POSIX_CP 1
#define ENABLE_FEATURE_NON_POSIX_CP 1
#ifdef MAKE_SUID
# define IF_FEATURE_NON_POSIX_CP(...) __VA_ARGS__ "CONFIG_FEATURE_NON_POSIX_CP"
#else
# define IF_FEATURE_NON_POSIX_CP(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_NON_POSIX_CP(...)
#undef CONFIG_FEATURE_VERBOSE_CP_MESSAGE
#define ENABLE_FEATURE_VERBOSE_CP_MESSAGE 0
#define IF_FEATURE_VERBOSE_CP_MESSAGE(...)
#define IF_NOT_FEATURE_VERBOSE_CP_MESSAGE(...) __VA_ARGS__
#define CONFIG_FEATURE_COPYBUF_KB 4
#define ENABLE_FEATURE_COPYBUF_KB 1
#ifdef MAKE_SUID
# define IF_FEATURE_COPYBUF_KB(...) __VA_ARGS__ "CONFIG_FEATURE_COPYBUF_KB"
#else
# define IF_FEATURE_COPYBUF_KB(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_COPYBUF_KB(...)
#define CONFIG_FEATURE_SKIP_ROOTFS 1
#define ENABLE_FEATURE_SKIP_ROOTFS 1
#ifdef MAKE_SUID
# define IF_FEATURE_SKIP_ROOTFS(...) __VA_ARGS__ "CONFIG_FEATURE_SKIP_ROOTFS"
#else
# define IF_FEATURE_SKIP_ROOTFS(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_SKIP_ROOTFS(...)
#undef CONFIG_MONOTONIC_SYSCALL
#define ENABLE_MONOTONIC_SYSCALL 0
#define IF_MONOTONIC_SYSCALL(...)
#define IF_NOT_MONOTONIC_SYSCALL(...) __VA_ARGS__
#define CONFIG_IOCTL_HEX2STR_ERROR 1
#define ENABLE_IOCTL_HEX2STR_ERROR 1
#ifdef MAKE_SUID
# define IF_IOCTL_HEX2STR_ERROR(...) __VA_ARGS__ "CONFIG_IOCTL_HEX2STR_ERROR"
#else
# define IF_IOCTL_HEX2STR_ERROR(...) __VA_ARGS__
#endif
#define IF_NOT_IOCTL_HEX2STR_ERROR(...)
#define CONFIG_FEATURE_HWIB 1
#define ENABLE_FEATURE_HWIB 1
#ifdef MAKE_SUID
# define IF_FEATURE_HWIB(...) __VA_ARGS__ "CONFIG_FEATURE_HWIB"
#else
# define IF_FEATURE_HWIB(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_HWIB(...)

/*
 * Applets
 */

/*
 * Coreutils
 */

#undef CONFIG_TEST
#define ENABLE_TEST 0
#define IF_TEST(...)
#define IF_NOT_TEST(...) __VA_ARGS__
#undef CONFIG_FEATURE_TEST_64
#define ENABLE_FEATURE_TEST_64 0
#define IF_FEATURE_TEST_64(...)
#define IF_NOT_FEATURE_TEST_64(...) __VA_ARGS__

#undef CONFIG_CHOWN
#define ENABLE_CHOWN 0
#define IF_CHOWN(...)
#define IF_NOT_CHOWN(...) __VA_ARGS__

#undef CONFIG_ECHO
#define ENABLE_ECHO 0
#define IF_ECHO(...)
#define IF_NOT_ECHO(...) __VA_ARGS__
#undef CONFIG_FEATURE_FANCY_ECHO
#define ENABLE_FEATURE_FANCY_ECHO 0
#define IF_FEATURE_FANCY_ECHO(...)
#define IF_NOT_FEATURE_FANCY_ECHO(...) __VA_ARGS__

#undef CONFIG_LS
#define ENABLE_LS 0
#define IF_LS(...)
#define IF_NOT_LS(...) __VA_ARGS__

#undef CONFIG_PRINTF
#define ENABLE_PRINTF 0
#define IF_PRINTF(...)
#define IF_NOT_PRINTF(...) __VA_ARGS__


/*
 * Editors
 */
#undef CONFIG_FEATURE_VI_ASK_TERMINAL
#define ENABLE_FEATURE_VI_ASK_TERMINAL 0
#define IF_FEATURE_VI_ASK_TERMINAL(...)
#define IF_NOT_FEATURE_VI_ASK_TERMINAL(...) __VA_ARGS__

/*
 * Miscellaneous Utilities
 */
#undef CONFIG_FEATURE_LESS_ASK_TERMINAL
#define ENABLE_FEATURE_LESS_ASK_TERMINAL 0
#define IF_FEATURE_LESS_ASK_TERMINAL(...)
#define IF_NOT_FEATURE_LESS_ASK_TERMINAL(...) __VA_ARGS__

#undef CONFIG_FEATURE_CROND_D
#define ENABLE_FEATURE_CROND_D 0
#define IF_FEATURE_CROND_D(...)
#define IF_NOT_FEATURE_CROND_D(...) __VA_ARGS__

/*
 * Process Utilities
 */
#undef CONFIG_IOSTAT
#define ENABLE_IOSTAT 0
#define IF_IOSTAT(...)
#define IF_NOT_IOSTAT(...) __VA_ARGS__
#undef CONFIG_LSOF
#define ENABLE_LSOF 0
#define IF_LSOF(...)
#define IF_NOT_LSOF(...) __VA_ARGS__
#undef CONFIG_MPSTAT
#define ENABLE_MPSTAT 0
#define IF_MPSTAT(...)
#define IF_NOT_MPSTAT(...) __VA_ARGS__
#undef CONFIG_NMETER
#define ENABLE_NMETER 0
#define IF_NMETER(...)
#define IF_NOT_NMETER(...) __VA_ARGS__
#undef CONFIG_PMAP
#define ENABLE_PMAP 0
#define IF_PMAP(...)
#define IF_NOT_PMAP(...) __VA_ARGS__
#undef CONFIG_POWERTOP
#define ENABLE_POWERTOP 0
#define IF_POWERTOP(...)
#define IF_NOT_POWERTOP(...) __VA_ARGS__
#undef CONFIG_PSTREE
#define ENABLE_PSTREE 0
#define IF_PSTREE(...)
#define IF_NOT_PSTREE(...) __VA_ARGS__
#undef CONFIG_PWDX
#define ENABLE_PWDX 0
#define IF_PWDX(...)
#define IF_NOT_PWDX(...) __VA_ARGS__
#undef CONFIG_SMEMCAP
#define ENABLE_SMEMCAP 0
#define IF_SMEMCAP(...)
#define IF_NOT_SMEMCAP(...) __VA_ARGS__
#undef CONFIG_TOP
#define ENABLE_TOP 0
#define IF_TOP(...)
#define IF_NOT_TOP(...) __VA_ARGS__
#undef CONFIG_FEATURE_TOP_CPU_USAGE_PERCENTAGE
#define ENABLE_FEATURE_TOP_CPU_USAGE_PERCENTAGE 0
#define IF_FEATURE_TOP_CPU_USAGE_PERCENTAGE(...)
#define IF_NOT_FEATURE_TOP_CPU_USAGE_PERCENTAGE(...) __VA_ARGS__
#undef CONFIG_FEATURE_TOP_CPU_GLOBAL_PERCENTS
#define ENABLE_FEATURE_TOP_CPU_GLOBAL_PERCENTS 0
#define IF_FEATURE_TOP_CPU_GLOBAL_PERCENTS(...)
#define IF_NOT_FEATURE_TOP_CPU_GLOBAL_PERCENTS(...) __VA_ARGS__
#undef CONFIG_FEATURE_TOP_SMP_CPU
#define ENABLE_FEATURE_TOP_SMP_CPU 0
#define IF_FEATURE_TOP_SMP_CPU(...)
#define IF_NOT_FEATURE_TOP_SMP_CPU(...) __VA_ARGS__
#undef CONFIG_FEATURE_TOP_DECIMALS
#define ENABLE_FEATURE_TOP_DECIMALS 0
#define IF_FEATURE_TOP_DECIMALS(...)
#define IF_NOT_FEATURE_TOP_DECIMALS(...) __VA_ARGS__
#undef CONFIG_FEATURE_TOP_SMP_PROCESS
#define ENABLE_FEATURE_TOP_SMP_PROCESS 0
#define IF_FEATURE_TOP_SMP_PROCESS(...)
#define IF_NOT_FEATURE_TOP_SMP_PROCESS(...) __VA_ARGS__
#undef CONFIG_FEATURE_TOPMEM
#define ENABLE_FEATURE_TOPMEM 0
#define IF_FEATURE_TOPMEM(...)
#define IF_NOT_FEATURE_TOPMEM(...) __VA_ARGS__
#undef CONFIG_UPTIME
#define ENABLE_UPTIME 0
#define IF_UPTIME(...)
#define IF_NOT_UPTIME(...) __VA_ARGS__
#undef CONFIG_FEATURE_UPTIME_UTMP_SUPPORT
#define ENABLE_FEATURE_UPTIME_UTMP_SUPPORT 0
#define IF_FEATURE_UPTIME_UTMP_SUPPORT(...)
#define IF_NOT_FEATURE_UPTIME_UTMP_SUPPORT(...) __VA_ARGS__
#undef CONFIG_FREE
#define ENABLE_FREE 0
#define IF_FREE(...)
#define IF_NOT_FREE(...) __VA_ARGS__
#undef CONFIG_FUSER
#define ENABLE_FUSER 0
#define IF_FUSER(...)
#define IF_NOT_FUSER(...) __VA_ARGS__
#undef CONFIG_KILL
#define ENABLE_KILL 0
#define IF_KILL(...)
#define IF_NOT_KILL(...) __VA_ARGS__
#undef CONFIG_KILLALL
#define ENABLE_KILLALL 0
#define IF_KILLALL(...)
#define IF_NOT_KILLALL(...) __VA_ARGS__
#undef CONFIG_KILLALL5
#define ENABLE_KILLALL5 0
#define IF_KILLALL5(...)
#define IF_NOT_KILLALL5(...) __VA_ARGS__
#undef CONFIG_PGREP
#define ENABLE_PGREP 0
#define IF_PGREP(...)
#define IF_NOT_PGREP(...) __VA_ARGS__
#undef CONFIG_PIDOF
#define ENABLE_PIDOF 0
#define IF_PIDOF(...)
#define IF_NOT_PIDOF(...) __VA_ARGS__
#undef CONFIG_FEATURE_PIDOF_SINGLE
#define ENABLE_FEATURE_PIDOF_SINGLE 0
#define IF_FEATURE_PIDOF_SINGLE(...)
#define IF_NOT_FEATURE_PIDOF_SINGLE(...) __VA_ARGS__
#undef CONFIG_FEATURE_PIDOF_OMIT
#define ENABLE_FEATURE_PIDOF_OMIT 0
#define IF_FEATURE_PIDOF_OMIT(...)
#define IF_NOT_FEATURE_PIDOF_OMIT(...) __VA_ARGS__
#undef CONFIG_PKILL
#define ENABLE_PKILL 0
#define IF_PKILL(...)
#define IF_NOT_PKILL(...) __VA_ARGS__
#undef CONFIG_PS
#define ENABLE_PS 0
#define IF_PS(...)
#define IF_NOT_PS(...) __VA_ARGS__
#undef CONFIG_FEATURE_PS_WIDE
#define ENABLE_FEATURE_PS_WIDE 0
#define IF_FEATURE_PS_WIDE(...)
#define IF_NOT_FEATURE_PS_WIDE(...) __VA_ARGS__
#undef CONFIG_FEATURE_PS_LONG
#define ENABLE_FEATURE_PS_LONG 0
#define IF_FEATURE_PS_LONG(...)
#define IF_NOT_FEATURE_PS_LONG(...) __VA_ARGS__
#undef CONFIG_FEATURE_PS_TIME
#define ENABLE_FEATURE_PS_TIME 0
#define IF_FEATURE_PS_TIME(...)
#define IF_NOT_FEATURE_PS_TIME(...) __VA_ARGS__
#undef CONFIG_FEATURE_PS_ADDITIONAL_COLUMNS
#define ENABLE_FEATURE_PS_ADDITIONAL_COLUMNS 0
#define IF_FEATURE_PS_ADDITIONAL_COLUMNS(...)
#define IF_NOT_FEATURE_PS_ADDITIONAL_COLUMNS(...) __VA_ARGS__
#undef CONFIG_FEATURE_PS_UNUSUAL_SYSTEMS
#define ENABLE_FEATURE_PS_UNUSUAL_SYSTEMS 0
#define IF_FEATURE_PS_UNUSUAL_SYSTEMS(...)
#define IF_NOT_FEATURE_PS_UNUSUAL_SYSTEMS(...) __VA_ARGS__
#undef CONFIG_RENICE
#define ENABLE_RENICE 0
#define IF_RENICE(...)
#define IF_NOT_RENICE(...) __VA_ARGS__
#undef CONFIG_BB_SYSCTL
#define ENABLE_BB_SYSCTL 0
#define IF_BB_SYSCTL(...)
#define IF_NOT_BB_SYSCTL(...) __VA_ARGS__
#undef CONFIG_FEATURE_SHOW_THREADS
#define ENABLE_FEATURE_SHOW_THREADS 0
#define IF_FEATURE_SHOW_THREADS(...)
#define IF_NOT_FEATURE_SHOW_THREADS(...) __VA_ARGS__
#undef CONFIG_WATCH
#define ENABLE_WATCH 0
#define IF_WATCH(...)
#define IF_NOT_WATCH(...) __VA_ARGS__

/*
 * Runit Utilities
 */
#undef CONFIG_SESTATUS
#define ENABLE_SESTATUS 0
#define IF_SESTATUS(...)
#define IF_NOT_SESTATUS(...) __VA_ARGS__

/*
 * Shells
 */
#ifdef MAKE_SUID
# define IF_CTTYHACK(...) __VA_ARGS__ "CONFIG_CTTYHACK"
#else
# define IF_CTTYHACK(...) __VA_ARGS__
#endif
#define IF_NOT_CTTYHACK(...)
#define CONFIG_HUSH 1
#define ENABLE_HUSH 1
#ifdef MAKE_SUID
# define IF_HUSH(...) __VA_ARGS__ "CONFIG_HUSH"
#else
# define IF_HUSH(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH(...)
#define CONFIG_HUSH_BASH_COMPAT 1
#define ENABLE_HUSH_BASH_COMPAT 1
#ifdef MAKE_SUID
# define IF_HUSH_BASH_COMPAT(...) __VA_ARGS__ "CONFIG_HUSH_BASH_COMPAT"
#else
# define IF_HUSH_BASH_COMPAT(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_BASH_COMPAT(...)
#define CONFIG_HUSH_BRACE_EXPANSION 1
#define ENABLE_HUSH_BRACE_EXPANSION 1
#ifdef MAKE_SUID
# define IF_HUSH_BRACE_EXPANSION(...) __VA_ARGS__ "CONFIG_HUSH_BRACE_EXPANSION"
#else
# define IF_HUSH_BRACE_EXPANSION(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_BRACE_EXPANSION(...)
#define CONFIG_HUSH_HELP 1
#define ENABLE_HUSH_HELP 1
#ifdef MAKE_SUID
# define IF_HUSH_HELP(...) __VA_ARGS__ "CONFIG_HUSH_HELP"
#else
# define IF_HUSH_HELP(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_HELP(...)
#define CONFIG_HUSH_INTERACTIVE 1
#define ENABLE_HUSH_INTERACTIVE 1
#ifdef MAKE_SUID
# define IF_HUSH_INTERACTIVE(...) __VA_ARGS__ "CONFIG_HUSH_INTERACTIVE"
#else
# define IF_HUSH_INTERACTIVE(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_INTERACTIVE(...)
#define CONFIG_HUSH_SAVEHISTORY 1
#define ENABLE_HUSH_SAVEHISTORY 1
#ifdef MAKE_SUID
# define IF_HUSH_SAVEHISTORY(...) __VA_ARGS__ "CONFIG_HUSH_SAVEHISTORY"
#else
# define IF_HUSH_SAVEHISTORY(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_SAVEHISTORY(...)
#define CONFIG_HUSH_JOB 1
#define ENABLE_HUSH_JOB 1
#ifdef MAKE_SUID
# define IF_HUSH_JOB(...) __VA_ARGS__ "CONFIG_HUSH_JOB"
#else
# define IF_HUSH_JOB(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_JOB(...)
#define CONFIG_HUSH_TICK 1
#define ENABLE_HUSH_TICK 1
#ifdef MAKE_SUID
# define IF_HUSH_TICK(...) __VA_ARGS__ "CONFIG_HUSH_TICK"
#else
# define IF_HUSH_TICK(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_TICK(...)
#define CONFIG_HUSH_IF 1
#define ENABLE_HUSH_IF 1
#ifdef MAKE_SUID
# define IF_HUSH_IF(...) __VA_ARGS__ "CONFIG_HUSH_IF"
#else
# define IF_HUSH_IF(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_IF(...)
#define CONFIG_HUSH_LOOPS 1
#define ENABLE_HUSH_LOOPS 1
#ifdef MAKE_SUID
# define IF_HUSH_LOOPS(...) __VA_ARGS__ "CONFIG_HUSH_LOOPS"
#else
# define IF_HUSH_LOOPS(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_LOOPS(...)
#define CONFIG_HUSH_CASE 1
#define ENABLE_HUSH_CASE 1
#ifdef MAKE_SUID
# define IF_HUSH_CASE(...) __VA_ARGS__ "CONFIG_HUSH_CASE"
#else
# define IF_HUSH_CASE(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_CASE(...)
#define CONFIG_HUSH_FUNCTIONS 1
#define ENABLE_HUSH_FUNCTIONS 1
#ifdef MAKE_SUID
# define IF_HUSH_FUNCTIONS(...) __VA_ARGS__ "CONFIG_HUSH_FUNCTIONS"
#else
# define IF_HUSH_FUNCTIONS(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_FUNCTIONS(...)
#define CONFIG_HUSH_LOCAL 1
#define ENABLE_HUSH_LOCAL 1
#ifdef MAKE_SUID
# define IF_HUSH_LOCAL(...) __VA_ARGS__ "CONFIG_HUSH_LOCAL"
#else
# define IF_HUSH_LOCAL(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_LOCAL(...)
#define CONFIG_HUSH_RANDOM_SUPPORT 1
#define ENABLE_HUSH_RANDOM_SUPPORT 1
#ifdef MAKE_SUID
# define IF_HUSH_RANDOM_SUPPORT(...) __VA_ARGS__ "CONFIG_HUSH_RANDOM_SUPPORT"
#else
# define IF_HUSH_RANDOM_SUPPORT(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_RANDOM_SUPPORT(...)
#define CONFIG_HUSH_EXPORT_N 1
#define ENABLE_HUSH_EXPORT_N 1
#ifdef MAKE_SUID
# define IF_HUSH_EXPORT_N(...) __VA_ARGS__ "CONFIG_HUSH_EXPORT_N"
#else
# define IF_HUSH_EXPORT_N(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_EXPORT_N(...)
#define CONFIG_HUSH_MODE_X 1
#define ENABLE_HUSH_MODE_X 1
#ifdef MAKE_SUID
# define IF_HUSH_MODE_X(...) __VA_ARGS__ "CONFIG_HUSH_MODE_X"
#else
# define IF_HUSH_MODE_X(...) __VA_ARGS__
#endif
#define IF_NOT_HUSH_MODE_X(...)
#undef CONFIG_MSH
#define ENABLE_MSH 0
#define IF_MSH(...)
#define IF_NOT_MSH(...) __VA_ARGS__
#undef CONFIG_FEATURE_SH_IS_ASH
#define ENABLE_FEATURE_SH_IS_ASH 0
#define IF_FEATURE_SH_IS_ASH(...)
#define IF_NOT_FEATURE_SH_IS_ASH(...) __VA_ARGS__
#define CONFIG_FEATURE_SH_IS_HUSH 1
#define ENABLE_FEATURE_SH_IS_HUSH 1
#ifdef MAKE_SUID
# define IF_FEATURE_SH_IS_HUSH(...) __VA_ARGS__ "CONFIG_FEATURE_SH_IS_HUSH"
#else
# define IF_FEATURE_SH_IS_HUSH(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_SH_IS_HUSH(...)
#undef CONFIG_FEATURE_SH_IS_NONE
#define ENABLE_FEATURE_SH_IS_NONE 0
#define IF_FEATURE_SH_IS_NONE(...)
#define IF_NOT_FEATURE_SH_IS_NONE(...) __VA_ARGS__
#undef CONFIG_FEATURE_BASH_IS_ASH
#define ENABLE_FEATURE_BASH_IS_ASH 0
#define IF_FEATURE_BASH_IS_ASH(...)
#define IF_NOT_FEATURE_BASH_IS_ASH(...) __VA_ARGS__
#undef CONFIG_FEATURE_BASH_IS_HUSH
#define ENABLE_FEATURE_BASH_IS_HUSH 0
#define IF_FEATURE_BASH_IS_HUSH(...)
#define IF_NOT_FEATURE_BASH_IS_HUSH(...) __VA_ARGS__
#define CONFIG_FEATURE_BASH_IS_NONE 1
#define ENABLE_FEATURE_BASH_IS_NONE 1
#ifdef MAKE_SUID
# define IF_FEATURE_BASH_IS_NONE(...) __VA_ARGS__ "CONFIG_FEATURE_BASH_IS_NONE"
#else
# define IF_FEATURE_BASH_IS_NONE(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_BASH_IS_NONE(...)
#define CONFIG_SH_MATH_SUPPORT 1
#define ENABLE_SH_MATH_SUPPORT 1
#ifdef MAKE_SUID
# define IF_SH_MATH_SUPPORT(...) __VA_ARGS__ "CONFIG_SH_MATH_SUPPORT"
#else
# define IF_SH_MATH_SUPPORT(...) __VA_ARGS__
#endif
#define IF_NOT_SH_MATH_SUPPORT(...) 
#undef CONFIG_SH_MATH_SUPPORT_64 
#define ENABLE_SH_MATH_SUPPORT_64 0
#ifdef MAKE_SUID
# define IF_SH_MATH_SUPPORT_64(...)
#else
# define IF_SH_MATH_SUPPORT_64(...)
#endif
#define IF_NOT_SH_MATH_SUPPORT_64(...) __VA_ARGS__
#define CONFIG_FEATURE_SH_EXTRA_QUIET 1
#define ENABLE_FEATURE_SH_EXTRA_QUIET 1
#ifdef MAKE_SUID
# define IF_FEATURE_SH_EXTRA_QUIET(...) __VA_ARGS__ "CONFIG_FEATURE_SH_EXTRA_QUIET"
#else
# define IF_FEATURE_SH_EXTRA_QUIET(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_SH_EXTRA_QUIET(...)
#undef CONFIG_FEATURE_SH_STANDALONE
#define ENABLE_FEATURE_SH_STANDALONE 0
#define IF_FEATURE_SH_STANDALONE(...)
#define IF_NOT_FEATURE_SH_STANDALONE(...) __VA_ARGS__
#undef CONFIG_FEATURE_SH_NOFORK
#define ENABLE_FEATURE_SH_NOFORK 0
#define IF_FEATURE_SH_NOFORK(...)
#define IF_NOT_FEATURE_SH_NOFORK(...) __VA_ARGS__
#define CONFIG_FEATURE_SH_HISTFILESIZE 1
#define ENABLE_FEATURE_SH_HISTFILESIZE 1
#ifdef MAKE_SUID
# define IF_FEATURE_SH_HISTFILESIZE(...) __VA_ARGS__ "CONFIG_FEATURE_SH_HISTFILESIZE"
#else
# define IF_FEATURE_SH_HISTFILESIZE(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_SH_HISTFILESIZE(...)


#define ENABLE_FEATURE_VERBOSE 0
